base/urls.py
from django.conf.urls import url
from . import views

app_name = 'base'


urlpatterns = [

    #home page
    url(r'^home/$', views.home, name='home'),


]

hera/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from programs import urls
from programs import views
from django.contrib.auth import views as auth_views
from base import urls


urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    #login page
    url(r'^$', auth_views.LoginView.as_view(), name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^programs/', include('programs.urls', namespace="programs")),
    url(r'^signup/', views.UserFormView.as_view(), name='register'),
    url(r'', include('Utenti.urls', namespace='utenti')),
    url(r'', include('base.urls', namespace='base'))
]

programs/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'programs'


urlpatterns = [

    #frontend homepage
    url(r'^$', views.AllProgramsView.as_view(), name='index'),

    #register page
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #login page
    url(r'^accounts/login/$', auth_views.LoginView.as_view(), name='login'),

    #single program page
    url(r'^(?P<pk>[0-9]+)/$', views.ProgramDetailView.as_view(), name='program'),

    #bookmark a program as a favourite
    url(r'^(?P<program_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),

    #remove a program from favourite
    url(r'^(?P<program_id>[0-9]+)/unfavourite/$', views.unfavourite, name='unfavourite'),

    #program create page
    url(r'^program/create/$', views.ProgramCreate.as_view(template_name="programs/create.html"), name='program-create'),

    #program update page  url programs/program_id
    url(r'^program/(?P<pk>[0-9]+)/$', views.ProgramUpdate.as_view(template_name="programs/update.html"), name='program-update'),

    #program delete page  url programs/program_id/delete
    url(r'^program/(?P<pk>[0-9]+)/delete/$', views.ProgramDelete.as_view(), name='program-delete'),

    #cycle create page
    url(r'^cycle/create/$', views.CycleCreate.as_view(template_name="programs/cycle-create.html"), name='cycle-create'),

    #cycle update page
    url(r'^cycle/(?P<pk>[0-9]+)/$', views.CycleUpdate.as_view(template_name="programs/cycle-update.html"), name='cycle-update'),

    #cycle delete page
    url(r'^cycle/(?P<pk>[0-9]+)/delete/$', views.CycleDelete.as_view(), name='cycle-delete'),

    #step create page
    url(r'^step/create/$', views.StepCreate.as_view(template_name="programs/step-create.html"), name='step-create'),

    #step update page
    url(r'^step/(?P<pk>[0-9]+)/$', views.StepUpdate.as_view(template_name="programs/step-update.html"), name='step-update'),

    #step delete page
    url(r'^step/(?P<pk>[0-9]+)/delete/$', views.StepDelete.as_view(), name='step-delete'),

    #API (get) all programs related to a user
    url(r'^api/', views.AllProgramsApi.as_view()),

]




urlpatterns = format_suffix_patterns(urlpatterns)

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required


#View associated to Home Page

@login_required
def home(request):
   return render_to_response('base/home.html')

base/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}Hera Control Administration Panel{% endblock %}</title>

    <!-- Load the path to static file specific for this template -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'programs/style.css' %}" />

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-toggleable-md">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#containerNavbarCenter" aria-controls="containerNavbarCenter" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-md-center" id="containerNavbarCenter">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="navbar-brand" href="{% url 'programs:index' %}">Hera</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="#">Program</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="#">Operate</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="#">Analyse</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="#">Settings</a>
              </li>
            </ul>
          </div>
        </nav>

        {% block content %}

        {% endblock %}

        <footer class="footer">
          <div class="container text-center">
              <span>Hera Control Admin Panel. Powered by <a class="text-light" href="http://ctaelectronics.com">CTA Electronics</span>
          </div>
        </footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    </body>
  </html>

base/templates/base/home.html
{% extends 'programs/base.html' %}
{% block title %}Hera Control: Home Page{% endblock %}

{% block content %}

<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading"><strong>Welcome to Hera Home Page</strong></h1>
      <p class="lead">This is the place to start.</p>
      <p>
        <!--<a href="#" class="btn btn-primary">Launch it</a>-->
        <!--<a href="#" class="btn btn-secondary">See Analytics</a>-->
      </p>
      <p>
    </div>
</section>

<div class="bg-white">
  <div class="container center-block">
    <div class="row">
      <div class="col-md-4 m-b-lg">
         <div class="panel panel-default">
           <div class="panel-body text-center">
             <h5 class="panel-title">Programming</h5>
             <p>This section is entirely dedicated to programming: see full list of programs, mark your favourite or create your owns.</p>
             <a href="/programs/" class="btn btn-primary"><span class="icon icon-add-user"></span> Start Programming</a><br><br>
           </div>
         </div>
       </div>
       <div class="col-md-4 m-b-lg">
          <div class="panel panel-default">
            <div class="panel-body text-center">
              <h5 class="panel-title">Remote Activities</h5>
              <p>Easily work remotely on your laundry equipment and launch programs, maintenance or special actions in just one click.</p>
              <a href="" class="btn btn-primary">Start Performing</a>
            </div>
          </div>
        </div>
        <div class="col-md-4 m-b-lg">
           <div class="panel panel-default">
             <div class="panel-body text-center">
               <h5 class="panel-title">Analytics</h5>
               <p>Track productivuty and other useful metrics to maximise the performance of your laundry activities.</p>
               <a href="" class="btn btn-primary"><span class="icon icon-add-user"></span> Start Analysing</a>
             </div>
           </div>
         </div>
    </div>
  </div>
</div>

















{% endblock %}