base/urls.py
from django.conf.urls import url
from . import views

app_name = 'base'


urlpatterns = [

    #home page
    url(r'^home/$', views.home, name='home'),


]

hera/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from programs import urls
from programs import views
from django.contrib.auth import views as auth_views
from base import urls


urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    #login page
    url(r'^$', auth_views.LoginView.as_view(), name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^programs/', include('programs.urls', namespace="programs")),
    url(r'^signup/', views.UserFormView.as_view(), name='register'),
    url(r'', include('Utenti.urls', namespace='utenti')),
    url(r'', include('base.urls', namespace='base'))
]

programs/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'programs'


urlpatterns = [

    #frontend homepage
    url(r'^$', views.AllProgramsView.as_view(), name='index'),

    #register page
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #login page
    url(r'^accounts/login/$', auth_views.LoginView.as_view(), name='login'),

    #single program page
    url(r'^(?P<pk>[0-9]+)/$', views.ProgramDetailView.as_view(), name='program'),

    #bookmark a program as a favourite
    url(r'^(?P<program_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),

    #remove a program from favourite
    url(r'^(?P<program_id>[0-9]+)/unfavourite/$', views.unfavourite, name='unfavourite'),

    #program create page
    url(r'^program/create/$', views.ProgramCreate.as_view(template_name="programs/create.html"), name='program-create'),

    #program update page  url programs/program_id
    url(r'^program/(?P<pk>[0-9]+)/$', views.ProgramUpdate.as_view(template_name="programs/update.html"), name='program-update'),

    #program delete page  url programs/program_id/delete
    url(r'^program/(?P<pk>[0-9]+)/delete/$', views.ProgramDelete.as_view(), name='program-delete'),

    #cycle create page
    url(r'^cycle/create/$', views.CycleCreate.as_view(template_name="programs/cycle-create.html"), name='cycle-create'),

    #cycle update page
    url(r'^cycle/(?P<pk>[0-9]+)/$', views.CycleUpdate.as_view(template_name="programs/cycle-update.html"), name='cycle-update'),

    #cycle delete page
    url(r'^cycle/(?P<pk>[0-9]+)/delete/$', views.CycleDelete.as_view(), name='cycle-delete'),

    #step create page
    url(r'^step/create/$', views.StepCreate.as_view(template_name="programs/step-create.html"), name='step-create'),

    #step update page
    url(r'^step/(?P<pk>[0-9]+)/$', views.StepUpdate.as_view(template_name="programs/step-update.html"), name='step-update'),

    #step delete page
    url(r'^step/(?P<pk>[0-9]+)/delete/$', views.StepDelete.as_view(), name='step-delete'),

    #API (get) all programs related to a user
    url(r'^api/', views.AllProgramsApi.as_view()),

]




urlpatterns = format_suffix_patterns(urlpatterns)

base/models.py
from django.db import models

# Create your models here.

programs/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class MotorSetting(models.Model):
    """Definzione dati motore"""
    """scelta del motore, da 1 a 6"""
    motor_number = models.CharField(max_length=50, unique=True, choices=[('Motor 1','Motor 1'), ('Motor 2','Motor 2'), ('Motor 3','Motor 3'), ('Motor 4', 'Motor 4'), ('Motor 5','Motor 5'), ('Motor 6','Motor 6'), ('Motor 7','Motor 7'), ('Motor 8','Motor 8'), ('Motor 9','Motor 9'), ('Motor 10','Motor 10'), ('Motor 11','Motor 11'), ('Motor 12','Motor 12'), ('Motor 13','Motor 13'), ('Motor 14','Motor 14'), ('Motor 15','Motor 15')])
    """tempo di rotazione in avanti, espresso in secondi"""
    forward_motion_time = models.IntegerField(

    )
    """tempo di pausa del motore, espresso in secondo"""
    pause_motion_time = models.IntegerField(

    )
    """tempo di rotazione inversa, espresso in secondi"""
    backward_motion_time = models.IntegerField(

    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.motor_number

class Output24(models.Model):
    output_position = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.output_position


class CustomRelay(models.Model):
    crelay_name = models.CharField("Custom Relay, Name", max_length=50)
    crelay_description = models.CharField("Custom Relay, Description", max_length=150)
    output = models.OneToOneField(Output24)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.crelay_name

class WaterInlet(models.Model):
    water_inlet_name = models.CharField("Water Type", max_length=50)
    water_inlet_description = models.CharField("Description of the inlet valve", max_length=150)
    output = models.OneToOneField(Output24)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.water_inlet_name


class Chemical(models.Model):
    chemical_name = models.CharField("Chemical Name", max_length=50)
    chemical_description = models.CharField("Chemical Description", max_length=150)
    output = models.OneToOneField(Output24)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.chemical_name

class Step(models.Model):
    """definizione del database che contiene gli step programmabili dall'utente"""
    step_name = models.CharField(max_length=50)
    step_description = models.TextField(max_length=250)
    water_inlet = models.ForeignKey(WaterInlet, blank=True, null=True)
    drain = models.CharField(max_length=30, choices=[('False', 'No'),('True', 'Yes')], blank=True, null=True)
    chemicals = models.ManyToManyField(Chemical)
    custom_relays = models.ManyToManyField(CustomRelay)
    """scelta del tipo di motore, da 1 a 15"""
    motor = models.ForeignKey(MotorSetting, on_delete=models.CASCADE)
    """assegnazione velocità motore espressa in giri al minuto"""
    motor_speed = models.IntegerField(
        validators=[MaxValueValidator(999), MinValueValidator(0)],
        blank=True,
        null=True
    )
    """settaggio fine step"""
    """livello"""
    stop_level = models.IntegerField(
        validators=[MaxValueValidator(100), MinValueValidator(0)],
        blank=True,
        null=True
    )
    """temperatura"""
    stop_temperature = models.IntegerField(
        validators=[MaxValueValidator(93), MinValueValidator(2)],
        blank=True,
        null=True
    )
    """tempo"""
    stop_time = models.IntegerField(
        blank=True,
        null=True
    )
    """watchdog"""
    wdt = models.IntegerField(
        blank=True,
        null=True
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.step_name + "  --  " + self.step_description

class Cycle(models.Model):
    """Definizione dei cicli liberamente configurabili. Ogni ciclo è composto da uno o più step"""
    cycle_type = models.CharField(max_length=150, choices=[('Pre-wash', 'Pre-wash'), ('Wash', 'Wash'), ('Rinse', 'Rinse'), ('Spin', 'Spin'), ('Unroll', 'Unroll')])
    cycle_name = models.CharField(max_length=250)
    cycle_description = models.CharField(max_length=250)
    steps = models.ManyToManyField(Step)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.cycle_name + "  --  " + self.cycle_description

class Program(models.Model):
    """Definizione dei programmi liberamente configurabili. Ogni programma si compone di uno o più cicli predefiniti dal Cliente"""
    program_name = models.CharField(max_length=50)
    program_description = models.CharField(max_length=250)
    cycles = models.ManyToManyField(Cycle)
    is_favourite = models.BooleanField(default="False")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('programs:program', kwargs={'pk': self.pk})

    def __str__(self):
        return self.program_name


class GeneralSetting(models.Model):
    """Definizione dei parametri generali"""
    language = models.CharField(max_length=100, choices=[('English', 'English'),('Italiano', 'Italiano'),('Español', 'Español'), ('Français', 'Français'), ('Deutsch', 'Deutsch')])
    degrees = models.CharField(max_length=100, choices=[('Celsius (C°)', 'Celsius (C°)'), ('Farenheit (F°)', 'Farenheit (F°)')])
    """Definizione dei settaggi base della macchina"""
    """Livello massimo di riscaldamento"""
    heat_max = models.IntegerField(

    )
    """Livello massimo di raffreddamento"""
    cool_max = models.IntegerField(

    )
    """Livello massimo di velocità del motore"""
    speed_max = models.IntegerField(

    )
    """Tempo di rallentamento centrifuga"""
    spin_braking = models.IntegerField(

    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class LogsParameter(models.Model):
    """Definizione dei parametri per log e analytics"""
    """Tempo di funzionamento espresso in ore"""
    uptime_hours = models.IntegerField
    """Tempo di inattività espresso in ore"""
    downtime_hours = models.IntegerField
    """Numero di lavaggi eseguiti al momento della richiesta"""
    num_washes_performed = models.IntegerField
    """Numero di errori visualizzati"""
    num_errors_displayed = models.IntegerField
    user = models.ForeignKey(User, on_delete=models.CASCADE)

programs/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Program, Cycle, Step, MotorSetting

#creating a class to bootstrap program form on frontend
class ProgramFormClass(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProgramFormClass, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control form-control-lg'
        })

    class Meta:
        model = Program
        fields = ['program_name', 'program_description', 'cycles']


#creating a class to bootstrap cycle form on frontend
class CycleFormClass(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CycleFormClass, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control form-control-lg'
        })

    class Meta:
        model = Cycle
        fields = ['cycle_name', 'cycle_description', 'steps']


#creating a class to bootstrap step form on frontend
class StepFormClass(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(StepFormClass, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control form-control-lg'
        })

    class Meta:
        model = Step
        fields = '__all__'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

base/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required


#View associated to Home Page

@login_required
def home(request):
   return render_to_response('base/home.html')

programs/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from .models import Step, Cycle, Program, MotorSetting, GeneralSetting
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm, ProgramFormClass, CycleFormClass, StepFormClass
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import ProgramSerializer



class AllProgramsView (LoginRequiredMixin, generic.ListView):
    template_name = 'programs/index.html'
    context_object_name = 'programs_list'

    def get_queryset(self):
         user = self.request.user
         queryset = Program.objects.filter(user=user)
         return queryset


class ProgramDetailView (LoginRequiredMixin, generic.DetailView):
    model = Program
    template_name = 'programs/program.html'


@login_required
def favourite(request, program_id):
    program = get_object_or_404(Program, pk=program_id)
    program.is_favourite=True;
    program.save()
    return render(request, 'programs/program.html', {'program': program})

@login_required
def unfavourite(request, program_id):
    program = get_object_or_404(Program, pk=program_id)
    program.is_favourite=False;
    program.save()
    return render(request, 'programs/program.html', {'program': program})


class ProgramCreate(LoginRequiredMixin, CreateView):
    model = Program
    form_class = ProgramFormClass


class ProgramUpdate(LoginRequiredMixin, UpdateView):
    model = Program
    form_class = ProgramFormClass


class ProgramDelete(LoginRequiredMixin,DeleteView):
    model = Program
    success_url = reverse_lazy('programs:index')


class CycleCreate(LoginRequiredMixin, CreateView):
    model = Cycle
    form_class = CycleFormClass


class CycleUpdate(LoginRequiredMixin, UpdateView):
    model = Cycle
    form_class = CycleFormClass


class CycleDelete(LoginRequiredMixin, DeleteView):
    model = Cycle
    success_url = reverse_lazy('programs:index')


class StepCreate(LoginRequiredMixin, CreateView):
    model = Step
    form_class = StepFormClass


class StepUpdate(LoginRequiredMixin, UpdateView):
    model = Step
    form_class = StepFormClass


class StepDelete(LoginRequiredMixin,DeleteView):
    model = Step
    success_url = reverse_lazy('programs:index')

#the following view regulates users registration
class UserFormView(View):
    form_class = UserForm
    template_name = 'programs/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    #process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            #storing the data but NOT SAVING them to db yet
            user = form.save(commit=False)

            #cleaning and normalizing data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            #saving to db
            user.save()

            #if credentials are correct, this returns a user object
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:

                    login(request, user)
                    return redirect('programs:index')

        return render(request, self.template_name, {'form': form})

#class che gestisce la richiesta API di tipo GET e POST (post al momento non attivato, vedi pass) per tutti i programmi associati ad un Utente
class AllProgramsApi(APIView):

    def get(self, request):
        user = self.request.user
        userprograms = Program.objects.filter(user=user)
        serializer = ProgramSerializer(userprograms, many=True)
        return Response(serializer.data)

    def post(self):
        pass

programs/templates/programs/action.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Program Page for Hera Project</title>

    <!-- Load the path to static file specific for this template -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'programs/style.css' %}" />

  </head>

  <body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

          <!--Hera Logo-->
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'programs:index' %}">Hera</a>
          </div>

        </div>
    </nav>

    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">All your programs, listed here</h1>
        <p class="lead">From this view you can easily see and manage your existing washing programs.</p>
        <p>
          <!--<a href="#" class="btn btn-primary">Launch it</a>-->
          <!--<a href="#" class="btn btn-secondary">See Analytics</a>-->
        </p>
      </div>
    </section>

    <div class="album text-muted">
      <div class="container">

        <div class="row">
          <div class="col-sm-4 py-4">
           <div class="card">
             {% if all_programs %}
               <h3>Here are all the programs:</h3>
               <ul>
                   {% for program in all_programs %}
                   <li><a href="/programs/{{ program.id }}/">{{ program.program_name }}</a></li>
                   {% endfor %}
                 </ul>
                 {% else %}
                   <h3>There's no program yet. Go ahead and create your first one :)</h3>
                 {% endif %}
             <p><h5>Would you like to modify this program?</h5></p>
             <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
             <a href="" class="btn btn-secondary">Modify it</a>
           </div>
         </div>
         <div class="col-sm-4 py-4">
          <div class="card">
             <p><h5>Would you like to use it as a template?</h5></p>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <a href="" class="btn btn-secondary">Use it</a>
          </div>
        </div>
        <div class="col-sm-4 py-4">
          <div class="card">
             <p><h5>Would you like to bookmark it as a favourite?</h5></p>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <a href="" class="btn btn-secondary">Bookmark it</a>
          </div>
        </div>
        <div class="container">
          <a href ="" class="btn btn-primarycta btn-block">Go Back to All Programs</a>
        </div>

      </div>
    </div>

      <footer class="text-muted">
        <div class="container">
          <p class="float-right">
            <a href="#">Back to top</a>
          </p>
          <p>Hera Control Admin Panel. Powered by <a href="http://ctaelectronics.com">CTA Electronics</a></p>
        </div>
      </footer>

      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

programs/templates/programs/create.html
{% extends 'programs/base.html' %}
{% block title %}Hera Control: Create a New Program{% endblock %}

{% block content %}

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Create a New Program</h1>
          <p class="lead">Please fill in the simple form below to start creating.</p>
          <p>
          </p>
        </div>
      </section>

      <div class="bg-secondaryctabig">
        <div class="container text-center">

                {% for field in form %}
                <form>
                {% csrf_token %}
                  <div class="form-group">
                    <label><strong>{{ field.label_tag }}</strong></label>
                    <div>{{ field }}</div>
                  </div>
                {% endfor %}
                  <button type="submit" class="btn btn-primarycta">Save this program</button>
                </form>


        </div>
      </div>















{% endblock %}

programs/templates/programs/index.html
{% extends 'programs/base.html' %}
{% block title %}Hera Control: All Programs{% endblock %}

{% block content %}
    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">All your programs, listed here</h1>
        <p class="lead">From this view you can easily see and manage your existing washing programs.</p>
        <p>
          <a href="#" class="btn btn-secondary">Add New</a>
          <!--<a href="#" class="btn btn-secondary">See Analytics</a>-->
        </p>
      </div>
    </section>

  {% if programs_list %}
    <div class="bg-primarycta">
      <div class="container">
        <div class="row">
                {% for program in programs_list %}
                  <div class="col-sm-4">
                    <div class="card">
                      <h6 class="card-header">Program ID: {{ program.id }}</h6>
                        <div class="card-block">
                          <a href="/programs/{{ program.id }}/" class"card-title"><h5>{{ program.program_name }}</h5></a>
                          <p class="card-text">{{ program.program_description }}</p>
                          <a href="/programs/{{ program.id }}/" class="btn btn-secondary">See detail</a>
                          <form action="{% url 'programs:program-update' program.id %}" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="program_id" value="{{ program.id }}">
                            <button type="submit" class="btn btn-secondary">
                              <span class="fa fa-pencil-square-o" aria-hidden="true" ></span>
                            </button>
                          </form>
                          <form action="{% url 'programs:program-delete' program.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="program_id" value="{{ program.id }}">
                            <button type="submit" class="btn btn-secondary">
                              <span class="fa fa-trash-o" aria-hidden="true" ></span>
                            </button>
                          </form>
                        </div>
                    </div>
                  </div>


                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                {% endfor %}
          </div>
        </div>
      </div>
    {% else %}
       <div class="bg-whitebig text-center">
        <h3>It looks like there's no program here.<br>How about creating the first?</h3><br>
        <a href='' class="btn btn-secondary btn-lg">Add a new program</a>
      </div>
    {% endif %}



<div class="bg-secondaryctabig">
 <div class="container">
  <div class="row">
      <div class="col-sm-4">
        <div class="media">
          <div class="row ">
            <div class="media-img  pull-left  col-sm-5  col-md-4 ">
              <div class="img-overlay "></div>
              <i class="fa fa-magic fa-4x"></i> </div>
            <div class="media-body   col-sm-7 col-md-8  ">
              <h4 class="media-heading"> <a href="">Create a New Program</a></h4>
              <p class="hidden-sm">Building a new program has never been easier.</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="media">
          <div class="row ">
            <div class="media-img  pull-left  col-sm-5  col-md-4 ">
              <div class="img-overlay "></div>
              <i class="fa fa-id-card-o fa-4x"></i> </div>
            <div class="media-body   col-sm-7 col-md-8  ">
              <h4 class="media-heading"> <a href="">Update Your Profile</a></h4>
              <p class="hidden-sm">Building a new program has never been easier.</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="media">
          <div class="row ">
            <div class="media-img  pull-left  col-sm-5  col-md-4 ">
              <div class="img-overlay "></div>
              <i class="fa fa-sliders fa-4x"></i> </div>
            <div class="media-body   col-sm-7 col-md-8  ">
              <h4 class="media-heading"> <a href="">See the Machine Settings</a></h4>
              <p class="hidden-sm">Check, update or modify machine parameters.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
   </div>
  </div>

{% endblock %}

programs/templates/programs/program.html
{% extends 'programs/base.html' %}
{% block title %}Hera Control: Program Details{% endblock %}

{% block content %}

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">{{ program.program_name }}</h1>
          <p class="lead">{{ program.program_description }}</p>
          <p>
                        {% if program.is_favourite %}
                                <form action="{% url 'programs:unfavourite' program.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Remove from Favourites" class="btn btn-secondary"></form>
                        {% else %}
                                <form action="{% url 'programs:favourite' program.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Bookmark it as a Favourite" class="btn btn-secondary"></form>
                        {% endif %}
          </p>
        </div>
      </section>

    <div class="bg-primarycta text-muted">
      <div class="container">
          <div class="row">
             {% if program.cycles %}
                {% for cycle in program.cycles.all %}
                  <div class="col-sm-4">
                   <div class="card">
                    <h6 class="card-header">Cycle ID: {{ cycle.id }}</h6>
                     <p><h5 style="color: #2196f3">{{ cycle.cycle_name }}</h5></p>
                     <p class="card-text"><lead>{{ cycle.cycle_description }}</lead></p>
                          {% if cycle.steps %}
                              <ul class="list-group list-group-flush">
                                  {% for step in cycle.steps.all %}
                                  <li class="list-group-item">
                                     <p class="card-text"><strong>Step {{ step.id }}: {{ step.step_name }}</strong> </p>
                                     <p class="card-text">{{ step.step_description }}</p>
                                    <p class="card-text"> <a class="btn btn-secondary"> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> View and Edit</a> <a class="btn btn-secondary"><i class="fa fa-trash" aria-hidden="true"></i> Delete</a></p>
                                  </li>
                                  {% endfor %}
                              </ul>
                          {% else %}
                                  <p>No steps contained in this cycle</p>
                            {% endif %}
                    </div>
                   </div>

            {% endfor %}
          {% endif %}
        </div>
        </div>
       </div>


      <div class="bg-secondarycta">
        <div class="container">

          <div class="row">
            <div class="col-sm-4 py-4">
             <div class="card">
               <p><h5>Would you like to modify this program?</h5></p>
               <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
               <a href="" class="btn btn-secondary"><i class="fa fa-pencil-square-o fa-3x" aria-hidden="true"></i></a>
             </div>
           </div>
           <div class="col-sm-4 py-4">
            <div class="card">
               <p><h5>Would you like to use it as a template?</h5></p>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <a href="" class="btn btn-secondary"><i class="fa fa-clone fa-3x" aria-hidden="true"></i></a>
            </div>
          </div>
          <div class="col-sm-4 py-4">
            <div class="card">
               <p><h5>Would you like to bookmark it as a favourite?</h5></p>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <a href="" class="btn btn-secondary"><i class="fa fa fa-thumb-tack fa-3x" aria-hidden="true"></i></a>
            </div>
          </div>
          <div class="bg-secondarycta">
            <a href ="" class="btn btn-primarycta btn-block">Go Back to All Programs</a>
          </div>

        </div>
      </div>

{% endblock %}